### ISSUE TITLE
[BUG] settings.range.min and settings.range.max do not inherit manually set date.min and date.max

### ISSUE THREAD

**Issue by whataboutpereira** [uvarov-frontend/vanilla-calendar-pro#289] opened 2024-08-13 22:43 UTC
date.min seems to have stopped working. The demo site calendar using `date.min: 1920-01-01` doesn't go past the default year 1970.

[demo link](https://vanilla-calendar.pro/docs/learn/date-range/start-and-end-of-existing-dates)
[codesandbox link](https://codesandbox.io/s/tpxzm3?file=%2Fcalendar.ts&utm_medium=sandpack)

**Comment by ghiscoding** [comment] 2024-08-15 13:42
Have you tried with `v2.9.7`? I've made 2 PRs #253 and #254 that were released in v2.9.7, it slightly modifies the date min/max code, but I'd be really surprised that it would affect anything. Anyway, could you try v2.9.7 or even older to confirm exactly which release worked and which doesn't

**Comment by ghiscoding** [comment] 2024-08-16 04:25
I found the reason of why it doesn't go below 1970 and it's caused by the code below. I think that code has been there for a long time and so the issue must have exists since a long time too. 

https://github.com/uvarov-frontend/vanilla-calendar-pro/blob/7c61e39b754a80c8852348947cffc53ab7fa5a18/package/src/scripts/helpers/setVariables.ts#L31-L32

and the reason why the code above is a problem is because the default date set is 1970-01-01, if the user sets the `date.min` to 1920 then that date is lower than `settings.range.min` and so the logic says that the is winning the check condition `settings.range.min` and so the minimum becomes 1970-01-01... if you instead use `settings.range.min` to set 1920-01-01, then it's the inverse and `date.min` wins because it's 1970-01-01.... so with the logic above `1970-01-01` is always the winner!

https://github.com/uvarov-frontend/vanilla-calendar-pro/blob/7c61e39b754a80c8852348947cffc53ab7fa5a18/package/src/scripts/default.ts#L16-L26

@uvarov-frontend considering the issue that I just mentioned, can the logic be changed? 

I did however find an alternative to the issue, if you set both `date.min` and `settings.range.min`, then it bypasses the issue because 1970-01-01 is not set anywhere since we overwrote both min dates to use 1920-01-01 which is bypassing the issue as shown below

![image](https://github.com/user-attachments/assets/23879578-61c4-449c-a7eb-9830a287d90f)

**Comment by whataboutpereira** [comment] 2024-08-16 06:57
Oh well, it seems we've been through this already in https://github.com/uvarov-frontend/vanilla-calendar-pro/issues/183 and I had forgotten about it. It's still very unintuitive. :/

**Comment by uvarov-frontend** [comment] 2024-08-16 07:27
I understand that the logic may seem confusing, but the whole essence is described in the documentation. So the code works correctly as intended.
https://vanilla-calendar.pro/docs/learn/date-range/start-and-end-of-existing-dates 
and
https://vanilla-calendar.pro/ru/docs/learn/date-range/maximum-and-minimum-date-to-display

**Comment by whataboutpereira** [comment] 2024-08-16 07:30
> I understand that the logic may seem confusing, but the whole essence is described in the documentation. So the code works correctly as intended. https://vanilla-calendar.pro/docs/learn/date-range/start-and-end-of-existing-dates

Yes, but this example in the docs still doesn't compute. date.min is 1920-01-01, but the calendar doesn't go past 1970 still.

**Comment by uvarov-frontend** [comment] 2024-08-16 07:34
> > I understand that the logic may seem confusing, but the whole essence is described in the documentation. So the code works correctly as intended. https://vanilla-calendar.pro/docs/learn/date-range/start-and-end-of-existing-dates
> 
> Yes, but this example in the docs still doesn't compute. date.min is 1920-01-01, but the calendar doesn't go past 1970 still.

Да, пример в документации не рабочий, я и забыл уже об этом.))
Вот так будет работать правильно:

**Closed** 2024-08-17 09:46 UTC
Labels: bug
